/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for ethtoolStatTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ethtoolStatTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "ethtoolStatTable_interface.h"

oid ethtoolStatTable_oid[] = { ETHTOOLSTATTABLE_OID };
int ethtoolStatTable_oid_size = OID_LENGTH(ethtoolStatTable_oid);

    ethtoolStatTable_registration  ethtoolStatTable_user_context;

void initialize_table_ethtoolStatTable(void);
void shutdown_table_ethtoolStatTable(void);


/**
 * Initializes the ethtoolStatTable module
 */
void
init_ethtoolStatTable(void)
{
    DEBUGMSGTL(("verbose:ethtoolStatTable:init_ethtoolStatTable","called\n"));

    /*
     * TODO:300:o: Perform ethtoolStatTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("ethtoolStatTable"))
        initialize_table_ethtoolStatTable();

} /* init_ethtoolStatTable */

/**
 * Shut-down the ethtoolStatTable module (agent is exiting)
 */
void
shutdown_ethtoolStatTable(void)
{
    if (should_init("ethtoolStatTable"))
        shutdown_table_ethtoolStatTable();

}

/**
 * Initialize the table ethtoolStatTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_ethtoolStatTable(void)
{
    ethtoolStatTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:ethtoolStatTable:initialize_table_ethtoolStatTable","called\n"));

    /*
     * TODO:301:o: Perform ethtoolStatTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize ethtoolStatTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("ethtoolStatTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _ethtoolStatTable_initialize_interface(user_context, flags);
} /* initialize_table_ethtoolStatTable */

/**
 * Shutdown the table ethtoolStatTable 
 */
void
shutdown_table_ethtoolStatTable(void)
{
    /*
     * call interface shutdown code
     */
    _ethtoolStatTable_shutdown_interface(&ethtoolStatTable_user_context);
}

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
ethtoolStatTable_pre_request(ethtoolStatTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:ethtoolStatTable:ethtoolStatTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform ethtoolStatTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* ethtoolStatTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
ethtoolStatTable_post_request(ethtoolStatTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:ethtoolStatTable:ethtoolStatTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform ethtoolStatTable post-request actions.
     */

    return MFD_SUCCESS;
} /* ethtoolStatTable_post_request */


/** @{ */
