/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 17548 2009-04-23 16:35:18Z hardaker $
 *
 * $Id:$
 */
#ifndef ETHTOOLSTATTABLE_OIDS_H
#define ETHTOOLSTATTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table ethtoolStatTable */
#define ETHTOOLSTATTABLE_OID              1,3,6,1,4,1,39178,100,1,1


#define COLUMN_ETHTOOLSTATNAME         1
    
#define COLUMN_ETHTOOLSTAT         2
    

#define ETHTOOLSTATTABLE_MIN_COL   COLUMN_ETHTOOLSTAT
#define ETHTOOLSTATTABLE_MAX_COL   COLUMN_ETHTOOLSTAT
    


#ifdef __cplusplus
}
#endif

#endif /* ETHTOOLSTATTABLE_OIDS_H */
