/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef ETHTOOLSTATTABLE_INTERFACE_H
#define ETHTOOLSTATTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "ethtoolStatTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _ethtoolStatTable_initialize_interface(ethtoolStatTable_registration * user_ctx,
                                    u_long flags);
void _ethtoolStatTable_shutdown_interface(ethtoolStatTable_registration * user_ctx);

ethtoolStatTable_registration *
ethtoolStatTable_registration_get( void );

ethtoolStatTable_registration *
ethtoolStatTable_registration_set( ethtoolStatTable_registration * newreg );

netsnmp_container *ethtoolStatTable_container_get( void );
int ethtoolStatTable_container_size( void );

    ethtoolStatTable_rowreq_ctx * ethtoolStatTable_allocate_rowreq_ctx(void);
void ethtoolStatTable_release_rowreq_ctx(ethtoolStatTable_rowreq_ctx *rowreq_ctx);

int ethtoolStatTable_index_to_oid(netsnmp_index *oid_idx,
                            ethtoolStatTable_mib_index *mib_idx);
int ethtoolStatTable_index_from_oid(netsnmp_index *oid_idx,
                              ethtoolStatTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void ethtoolStatTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* ETHTOOLSTATTABLE_INTERFACE_H */
/** @} */
