/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id:$
 */
#ifndef ETHTOOLSTATTABLE_DATA_SET_H
#define ETHTOOLSTATTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */


#ifdef __cplusplus
}
#endif

#endif /* ETHTOOLSTATTABLE_DATA_SET_H */
