/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file ethtoolStatTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef ETHTOOLSTATTABLE_DATA_GET_H
#define ETHTOOLSTATTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ethtoolStatTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * ETHTOOL-MIB::ethtoolStatTable is subid 1 of ethtool.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.39178.100.1.1, length: 10
*/
    /*
     * indexes
     */

    int ethtoolStat_get( ethtoolStatTable_rowreq_ctx *rowreq_ctx, U64 * ethtoolStat_val_ptr );


int ethtoolStatTable_indexes_set_tbl_idx(ethtoolStatTable_mib_index *tbl_idx, long ifIndex_val, char *ethtoolStatName_val_ptr,  size_t ethtoolStatName_val_ptr_len);
int ethtoolStatTable_indexes_set(ethtoolStatTable_rowreq_ctx *rowreq_ctx, long ifIndex_val, char *ethtoolStatName_val_ptr,  size_t ethtoolStatName_val_ptr_len);




#ifdef __cplusplus
}
#endif

#endif /* ETHTOOLSTATTABLE_DATA_GET_H */
/** @} */
